# Generated by Django 5.0 on 2024-01-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='2a161305043c86ef88abe9693611b44e', max_length=32),
        ),
    ]
