# Generated by Django 5.0 on 2024-01-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='43a538c78fb8099ee114e3c2e3b48558', max_length=32),
        ),
    ]
