# Generated by Django 5.0 on 2024-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='a722475ee32b7e8d3436fedff48b0064', max_length=32),
        ),
    ]
