# Generated by Django 5.0 on 2024-01-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
