# Generated by Django 5.0 on 2024-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='eb1960f8efa2f4f415bc1c0e6cfa7727', max_length=32),
        ),
    ]
