# Generated by Django 5.0 on 2024-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='86540b575033d571aa276b12a20998e4', max_length=32),
        ),
    ]
