# Generated by Django 5.0 on 2024-01-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, default='93093c686e604a8be5dabb30c4e8f92f', max_length=32, null=True),
        ),
    ]
