# Generated by Django 5.0 on 2024-01-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='1bb7ba72a605b8606c2f2c311ac88147', max_length=32),
        ),
    ]
