# Generated by Django 5.0 on 2023-12-21 08:15

import authentication.usermanager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.usermanager.UserManager()),
            ],
        ),
    ]
