# Generated by Django 5.0 on 2024-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='0b2331d063707de1c4535a90edfe42bb', max_length=32),
        ),
    ]
