# Generated by Django 5.0 on 2024-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='c25804d1a3e304098741befd0960aa63', max_length=32),
        ),
    ]
