# Generated by Django 5.0 on 2023-12-25 14:39

import authentication.usermanager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.usermanager.UserManager()),
            ],
        ),
    ]
