# Generated by Django 5.0 on 2024-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='584a98c0237159d3b68e5136275a0bf4', max_length=32),
        ),
    ]
