# Generated by Django 5.0 on 2024-01-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='96d6ffd13a45690167f72a72085181c9', max_length=32),
        ),
    ]
