# Generated by Django 5.0 on 2024-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='ab78c0cbbed37974dc618b7c5957e474', max_length=32),
        ),
    ]
